### ISSUE TITLE
It can't find reference to indicator container. 

### ISSUE THREAD

**Issue by shakarbhattarai** [PaoloRotolo/AppIntro#127]
java.lang.RuntimeException: Unable to start activity ComponentInfo{np.com.sabinb.nepalfeed/np.com.sabinb.nepalfeed.AppIntroduction}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2345)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2405)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:149)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1324)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:211)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5315)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:736)
                                                                          Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference
                                                                             at com.github.paolorotolo.appintro.AppIntro.initController(AppIntro.java:225)
                                                                             at com.github.paolorotolo.appintro.AppIntro.onCreate(AppIntro.java:183)
                                                                             at android.app.Activity.performCreate(Activity.java:5933)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2405) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:149) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1324) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:211) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5315) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:736)

**Comment by Andrew-Quebe** [comment]
@shakarbhattarai please include all of your code before opening an issue with a crash report in it. I need more information...show me some code, explain what you've tried already, etc. Reopen a new issue with all of this information. Thank you :)

**Comment by amitav13** [comment]
I'm getting a similar crash, can consistently reproduce it: [repo here](https://gitlab.com/amitav13/vipassana-quotes/tree/appintro_crash)

`10-01 18:09:03.798 10408-10408/com.amitavkhandelwal.vipassanaquotes E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: com.amitavkhandelwal.vipassanaquotes, PID: 10408
                                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amitavkhandelwal.vipassanaquotes/com.amitavkhandelwal.vipassanaquotes.intro.IntroActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference
                                                                                          at com.github.paolorotolo.appintro.AppIntroBase.initController(AppIntroBase.java:236)
                                                                                          at com.github.paolorotolo.appintro.AppIntroBase.onPostCreate(AppIntroBase.java:158)
                                                                                          at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1199)
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
`
