### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by saru95** [PaoloRotolo/AppIntro#135]
I am using the similar example given in docs as follows . No idea what is causing the error .

Error: 
```
FATAL EXCEPTION: main
                                                                         Process: com.dorkduck.blurbsmash, PID: 22265
                                                                         android.util.SuperNotCalledException: Activity {com.dorkduck.blurbsmash/com.dorkduck.blurbsmash.MainActivity} did not call through to super.onCreate()
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2259)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:147)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5234)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
```

MainActivity.java
```
package com.dorkduck.blurbsmash;

import android.content.Intent;
import android.content.SharedPreferences;
import android.preference.PreferenceManager;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import com.github.paolorotolo.appintro.*;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        //  Declare a new thread to do a preference check
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                //  Initialize SharedPreferences
                SharedPreferences getPrefs = PreferenceManager
                        .getDefaultSharedPreferences(getBaseContext());

                //  Create a new boolean and preference and set it to true
                boolean isFirstStart = getPrefs.getBoolean("firstStart", true);

                //  If the activity has never started before...
                if (isFirstStart) {

                    //  Launch app intro
                    Intent i = new Intent(MainActivity.this, TutorialInto.class);
                    startActivity(i);

                    //  Make a new preferences editor
                    SharedPreferences.Editor e = getPrefs.edit();

                    //  Edit preference to make it false because we don't want this to run again
                    e.putBoolean("firstStart", false);

                    //  Apply changes
                    e.apply();
                }
            }
        });

        // Start the thread
        t.start();
    }
}
```

TutorialInto.java
```
package com.dorkduck.blurbsmash;

import android.Manifest;
import android.graphics.Color;
import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.View;

import com.github.paolorotolo.appintro.*;

public class TutorialInto extends AppIntro2 {

    // Please DO NOT override onCreate. Use init
    @Override
    public void init(Bundle savedInstanceState) {

        // Instead of fragments, you can also use our default slide
        // Just set a title, description, background and image. AppIntro will do the rest
        addSlide(AppIntroFragment.newInstance("dasdasd", "dasdasd",R.drawable.appimage, Color.parseColor("#3F51B5")));

        // OPTIONAL METHODS

        // SHOW or HIDE the statusbar
        showStatusBar(true);

        // Edit the color of the nav bar on Lollipop+ devices
        //setNavBarColor(Color.parseColor("#3F51B5"))

        // Turn vibration on and set intensity
        // NOTE: you will need to ask VIBRATE permission in Manifest if you haven't already
        setVibrate(true);
        setVibrateIntensity(30);

        // Animations -- use only one of the below. Using both could cause errors.
        setFadeAnimation(); // OR
        //setZoomAnimation(); // OR
        //setFlowAnimation(); // OR
        //setSlideOverAnimation(); // OR
        //setDepthAnimation(); // OR
        //etCustomTransformer(yourCustomTransformer);

        // Permissions -- takes a permission and slide number
        askForPermissions(new String[]{Manifest.permission.CAMERA}, 3);
    }

    @Override
    public void onNextPressed() {
        // Do something when users tap on Next button.
    }

    @Override
    public void onDonePressed() {
        // Do something when users tap on Done button.
        finish();
    }

    @Override
    public void onSlideChanged() {
        // Do something when slide is changed
    }
}
```

**Comment by Andrew-Quebe** [comment]
you need to call super.onCreate() before declaring the runnable. it's also advised that you do the thread after everything else in onCreate. this would mean after you've set your content view (setContentView) and anything else.

**Comment by saru95** [comment]
can you please edit the code above and explain ?

**Comment by Andrew-Quebe** [comment]
@saru95 I don't write rewrite code for people :) call this in your Main Activity: `super.onCreate(savedInstanceState);`
