### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/paolorotolo/appintro/R$layout

### ISSUE THREAD

**Issue by arpitjoshi** [PaoloRotolo/AppIntro#205]
Process: cross.trainer.app, PID: 20994
                                                                   java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/paolorotolo/appintro/R$layout;
                                                                       at com.github.paolorotolo.appintro.AppIntro2.onCreate(AppIntro2.java:66)
                                                                       at android.app.Activity.performCreate(Activity.java:6010)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.paolorotolo.appintro.R$layout" on path: DexPathList[[dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-support-annotations-23.2.1_b4c0edb6674044b91de51719d5368841f4490dd8-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-internal_impl-23.2.1_e4a36e50a9e17bd0cf88efb19694ad35061e3426-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-httpclient-4.3.6_b2e3f6f12ff68d208c683974a02d8f93fb0896f1-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-com.github.paolorotolo-appintro-3.4.0_c4f8c27e04effe4cd1c32c87613a0327b52d60c5-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-com.android.support-support-vector-drawable-23.2.1_ef0171502b4dfd01d8a51de1f89e10e222ee0291-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-com.android.support-support-v4-23.2.1_4ae9b1e41f0aba253b2bc5350beff27fea866ae3-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-com.android.support-recyclerview-v7-23.2.1_67edd5fd77ce6cf6dbc713d24e4146ee4752d667-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-com.android.support-design-23.2.1_a9d9501b817135ef14093d6e79c378ba1a43b46e-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-com.android.support-appcompat-v7-23.2.1_1e81da16004f3fda182b78b3376cffe7cd739005-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-23.2.1_52e6c82ffc6b224833c75f5b0e2e2c357bcbcef2-classes.dex", dex file "/data/data/cross.trainer.app/files/instant-run/dex/slice-android-async-http-1.4.9_74fbc58af7d0d5af9528051b958d1d4cee559067-classes.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /vendor/lib, /system/lib]]
                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                   	at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader

**Comment by maxee** [comment]
This is related to the new gradle plugin v2.0.x and the new instant run feature in Android studio. Try to clean the project by clicking Build -> clean Project in Android studio.

**Comment by arpitjoshi** [comment]
Thanks maxee, it worked after build clean.
