### ISSUE TITLE
Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference

### ISSUE THREAD

**Issue by thedevleon** [PaoloRotolo/AppIntro#256]
I'm getting the following error when trying to start my app which uses the AppIntro in a simple Activity.

```
E/AndroidRuntime: FATAL EXCEPTION: main

                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{.../...app.IntroActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                            at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference
                                                                            at com.github.paolorotolo.appintro.AppIntroBase.initController(AppIntroBase.java:242)
                                                                            at com.github.paolorotolo.appintro.AppIntroBase.onPostCreate(AppIntroBase.java:161)
                                                                            at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1188)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2398)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                            at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

IntroActivity.java:
```
public class IntroActivity extends AppIntro {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        setTheme(R.style.AppTheme);

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_intro);

        // Add your slide's fragments here.
        // AppIntro will automatically generate the dots indicator and buttons.
        addSlide(IntroSlide.newInstance());
        addSlide(PatternSlide.newInstance());
        addSlide(AppSlide.newInstance());
        addSlide(ShortcutSlide.newInstance());
        addSlide(TrySlide.newInstance());


    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        Intent intent = new Intent(this, MainActivity.class);
        startActivity(intent);
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        Intent intent = new Intent(this, MainActivity.class);
        startActivity(intent);
    }

    @Override
    public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        super.onSlideChanged(oldFragment, newFragment);
        // Do something when the slide changes.
    }
}
```

IntroSlide.java
```
public class IntroSlide extends Fragment {
    public static IntroSlide newInstance() {
        IntroSlide sampleSlide = new IntroSlide();
        return sampleSlide;
    }

    public IntroSlide() {}

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        return inflater.inflate(R.layout.slide_intro, container, false);
    }


}
```

slide_intro.xml

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#222222">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="0dp"
        android:layout_gravity="center"
        android:gravity="center"
        android:paddingLeft="32dp"
        android:layout_weight="3"
        android:fontFamily="sans-serif-thin"
        android:textColor="#ffffff"
        android:paddingRight="32dp"
        android:textSize="28sp"
        android:text="Welcome!"/>

    <LinearLayout
        android:layout_width="fill_parent"
        android:layout_height="0dp"
        android:orientation="vertical"
        android:gravity="center"
        android:layout_weight="5">

        <ImageView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center"
            android:paddingLeft="16dp"
            android:paddingRight="16dp"
            android:src="@drawable/ic_visibility_black_24dp"/>
    </LinearLayout>
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="0dp"
        android:layout_weight="3"
        android:layout_gravity="center"
        android:gravity="center"
        android:textColor="#ffffff"
        android:paddingLeft="64dp"
        android:paddingRight="64dp"
        android:textSize="16sp"
        android:text="Welcome to the app!"/>
    <TextView
        android:layout_width="fill_parent"
        android:layout_height="64dp" />

</LinearLayout>
```

When following the stack to AppIntroBase.java:242, which is the second line here:

```
        FrameLayout indicatorContainer = (FrameLayout) findViewById(R.id.indicator_container);
        indicatorContainer.addView(mController.newInstance(this));
```

and setting a breakpoint at the first statement, it turns out that `indicatorContainer` == null, which is is why `indicatorContainer.addView` fails...

Any idea why this is happening?

**Comment by thedevleon** [comment]
Turns out 
```setContentView(R.layout.activity_intro);``` was the culprit. Makes sense.

**Comment by IzaqueRolim** [comment]
Thaks man, u resolve my bug <3
