### ISSUE TITLE
ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by plays2** [PaoloRotolo/AppIntro#264]
Please check off the following things BEFORE submitting a new issue. Any issues that do not properly follow this format will be closed without discussion. If you're requesting to have your app added to the list, you can erase the list and provide your app's name and play store listing link. Thanks!

[X] What you've tried (include code snippets, or whole files as necessary):

Following the tutorial. 
` 

    public class OpenActivity extends AppIntro2 {

        @Override
        public void onCreate(Bundle savedInstanceState, PersistableBundle persistentState) {

            super.onCreate(savedInstanceState, persistentState);
            addSlide(AppIntroFragment.newInstance("Title", "Description", R.drawable.ic_icon, R.color.colorBG));
            addSlide(AppIntroFragment.newInstance("Title", "Description", R.drawable.image, R.color.colorBG));
            addSlide(AppIntroFragment.newInstance("Title", "Description", R.drawable.image, R.color.colorBG));
            addSlide(AppIntroFragment.newInstance("Title", "Description'", R.drawable.image, R.color.colorBG));
            addSlide(AppIntroFragment.newInstance("Title", "Description", R.drawable.image, R.color.colorBG));
            addSlide(AppIntroFragment.newInstance("Title", "Description", R.drawable.image, R.color.colorBG));

            setFlowAnimation();

            askForPermissions(new String[]{android.Manifest.permission.WRITE_EXTERNAL_STORAGE, android.Manifest.permission.READ_EXTERNAL_STORAGE}, 5);

        }

        @Override
        public void onSkipPressed(Fragment currentFragment) {
            super.onSkipPressed(currentFragment);
            startActivity(new Intent(this, MainActivity.class));
        }

        @Override
        public void onDonePressed(Fragment currentFragment) {
            super.onDonePressed(currentFragment);
            startActivity(new Intent(this, MainActivity.class));
        }

        @Override
        public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
            super.onSlideChanged(oldFragment, newFragment);
        }
    }

`

[ ] What you thought should happen:

I should have a working intro page for my app

[ ] What actually happened:

ArrayIndexOutOfBoundsException as soon as the activity is launched:

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.diragi.regram, PID: 9535
                  java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                      at java.util.Vector.arrayIndexOutOfBoundsException(Vector.java:907)
                      at java.util.Vector.elementAt(Vector.java:328)
                      at java.util.Vector.get(Vector.java:442)
                      at com.github.paolorotolo.appintro.PagerAdapter.getItem(PagerAdapter.java:31)
                      at com.github.paolorotolo.appintro.AppIntroBase$3.run(AppIntroBase.java:154)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7229)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

S.O.S please someone help me

**Comment by alextel69** [comment]
Same here. Try decrease version of AppIntro in `build.gradle`

**Comment by plays2** [comment]
@alextel69 that fixed it, thanks!
