### ISSUE TITLE
NPE on addView at first start of app

### ISSUE THREAD

**Issue by amitav13** [PaoloRotolo/AppIntro#324]
**AppIntro Version**: 4.1.0

**Device/Android Version**: Reproduced on Nexus 6P API 24, Nexus 5 API 19 Android Studio Emulators

**Issue details / Repro steps / Use case background**: I'm trying to have AppIntro show up on first start of the app. Crash occurs as soon as the app loads up. I'm using the template that's provided in this repo to determine if it is the first start of the app. 

**Your Code**:
IntroActivity:
 ```java
//Also occurs with AppIntro2
public class IntroActivity extends AppIntro {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_intro);
        addSlide(new IntroTextFragment());
        //This also does not fix the crash
        //addSlide(AppIntroFragment.newInstance("Welcome to Vipassana Quotes", "This app is recommended " +
        //        "for people who have done Vipassana once already.", R.drawable.ic_notifications_black_24dp, getResources().getColor(R.color.colorPrimary)));
    }
}
```

activity_intro.xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/activity_intro"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.amitavkhandelwal.vipassanaquotes.intro.IntroActivity">

</RelativeLayout>
```

IntroTextFragment:
```java
public class IntroTextFragment extends Fragment {


    public IntroTextFragment() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_intro_text, container, false);
    }

}
```

MainActivity:

```java
public class MainActivity extends AppCompatActivity {

    public static final String TAG = MainActivity.class.getSimpleName();
    @BindView(R.id.all_quotes_recyclerview) RecyclerView allQuotesRecyclerView;
    private RealmAsyncTask transaction;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        //  Declare a new thread to do a preference check
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                //  Initialize SharedPreferences
                SharedPreferences getPrefs = PreferenceManager
                        .getDefaultSharedPreferences(getBaseContext());

                //  Create a new boolean and preference and set it to true
                boolean isFirstStart = getPrefs.getBoolean("firstStart", true);

                //  If the activity has never started before...
                if (isFirstStart) {

                    //  Launch app intro
                    Intent i = new Intent(MainActivity.this, IntroActivity.class);
                    startActivity(i);

                    //  Make a new preferences editor
                    SharedPreferences.Editor e = getPrefs.edit();

                    //  Edit preference to make it false because we don't want this to run again
                    e.putBoolean("firstStart", false);

                    //  Apply changes
                    e.apply();
                }
            }
        });

        // Start the thread
        t.start();
        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);
        transaction = RealmUtils.createRealmDbIfNeeded(this);

        QuotesAdapter allQuotesAdapter = new QuotesAdapter(RealmUtils.getAllQuotes());
        allQuotesRecyclerView.setAdapter(allQuotesAdapter);
        LinearLayoutManager layoutManager = new LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false);
        allQuotesRecyclerView.setLayoutManager(layoutManager);
    }

    @Override
    public void onStop () {
        if (transaction != null && !transaction.isCancelled()) {
            transaction.cancel();
        }
        super.onStop();
    }
}
```

**Stack trace / LogCat**:
```ruby
10-04 11:56:36.765 3045-3045/com.amitavkhandelwal.vipassanaquotes E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.amitavkhandelwal.vipassanaquotes, PID: 3045
                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amitavkhandelwal.vipassanaquotes/com.amitavkhandelwal.vipassanaquotes.intro.IntroActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference
                                                                                        at com.github.paolorotolo.appintro.AppIntroBase.initController(AppIntroBase.java:236)
                                                                                        at com.github.paolorotolo.appintro.AppIntroBase.onPostCreate(AppIntroBase.java:158)
                                                                                        at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1199)
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 

```

Repo that reproduces this issue: https://gitlab.com/amitav13/vipassana-quotes/tree/appintro_crash

**Comment by Andrew-Quebe** [comment]
Thanks for filling out the template accurately! What happens if you put your thread code after your resource binding and `setContentView`? I believe this is why it's crashing...my implementations of the library have the thread code at the bottom of the `onCreate` method to ensure everything loads on the MainActivity.

Little background info here: your main activity launches from the icon press. But...when onCreate is called, it launches the Intro activity straight away. Here's the thing with that though: there's actually two activities running. Your main activity, and the intro. Your main activity is just hidden behind the intro, and therefore is still loading everything it needs to. When the intro closes, it calls `finish()` which acts like the back button: it goes back to whatever activity is under it. Sometimes that's the launcher, sometimes that's the main activity of an app like in this case. 

Try the aforementioned solution, and if that doesn't work, let us know.

**Comment by amitav13** [comment]
Thanks for the quick response!

Moved the setContentView and ButterKnife.bind(this) before the thread.start(), but it doesn't seem to have an effect.

What you're saying does make sense, but it doesn't seem to be what's at play here. The stacktrace points to AppIntroBase.initController having a null reference. This AppIntro-related code comes into play only while instantiating the IntroActivity, so I would guess that AppIntro is trying to get a reference to the view of IntroActivity before its inflated.

**Comment by Andrew-Quebe** [comment]
I read that in the exception as I typed my response. @avluis any ideas? I'm at a bit of a loss 📦 

@amitav13 have you tried different lib versions? Maybe it's only in 4.1.0 or 4.0.0. I'm just trying to narrow stuff down.

**Comment by amitav13** [comment]
Same crash, slightly different line numbers on the stacktrace with 4.0.0: 
```ruby
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference
                                                                                          at com.github.paolorotolo.appintro.AppIntroBase.initController(AppIntroBase.java:242)
                                                                                          at com.github.paolorotolo.appintro.AppIntroBase.onPostCreate(AppIntroBase.java:161)
                                                                                          at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1199)
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

Not seeing a crash with 3.3.0, though I had to modify IntroActivity to fit with the 3.x API:

```java
public class IntroActivity extends AppIntro {

    @Override
    public void init(@Nullable Bundle savedInstanceState) {
        setContentView(R.layout.activity_intro);
        addSlide(new IntroTextFragment());
    }

    @Override
    public void onSkipPressed() {

    }

    @Override
    public void onNextPressed() {

    }

    @Override
    public void onDonePressed() {

    }

    @Override
    public void onSlideChanged() {

    }


}
```

**Comment by Andrew-Quebe** [comment]
Okay good...so we know it's something wrong with 4.x. @avluis I'll let you take a look if you can.

**Comment by amitav13** [comment]
Found the culprit thanks to #256 : setContentView() in IntroActivity. Removing it gets rid of the crash. Thanks for the help!

**Comment by Andrew-Quebe** [comment]
@avluis I think we should file this as a bug...if it's possible to fix it. That way there's no possible way this will happen. Maybe we can override setContentView in the lib so that it just doesn't run? In other words, if people call it in their code, it's just redundant and maybe warns them through annotations or something.

**Comment by avluis** [comment]
@Andrew-Quebe I'm awake now (you now, time zones and all lol, who needs them) -- anyways -- read the issue, saw the issue, then noticed it wasn't noticed...
I'll do a bit of research to figure out if we can warn about having `setContentView();` on implementations~
Not sure about calling it a bug though -- that is, if they follow the README and all the examples.

**Comment by amitav13** [comment]
@avluis Since this causes the library to become completely unusable, I'd think it would be better if AppIntro overrode it and set it to final. There's no functionality that's lost since AppIntro is supposed to set the view anyway right? Just my two cents.

**Comment by avluis** [comment]
@amitav13 And how do you propose we keep developers from using `setContentView();` whenever they wish?

We used to make use of an init() method, but that was frowned upon -- so `onCreateView()` is the way to go - but even then, you could just call `setContentView()` there as well and undo what the library does for you.
If you have any ideas of what logic we need to implement or a method to override, I'm all ears~

**Comment by amitav13** [comment]
@avluis you can make the `setContentView()` methods final in `AppIntro` like this: 

```java
@Override
    public final void setContentView(@LayoutRes int layoutResID) {
        //Don't call super here!
    }
```
It does feel a little hacky though. Maybe add in a lint warning instead? [Timber](https://github.com/JakeWharton/timber) has a lot of nice lint messages, you can pick up samples from that.

**Comment by avluis** [comment]
@amitav13 Unfortunately the override approach is something I won't consider, as it may have unintended side-effects for users -- but the lint warning, yes, that is a much better option -- will take a look at `Timber`.

**Comment by avluis** [comment]
@amitav13 And it looks like making use of lint forces the AppIntro library to be over the allowable method count...
Going to give the hack a few tests~

**Comment by amitav13** [comment]
@avluis if you're interested in cutting down the method count, have a look at this [plugin](https://github.com/KeepSafe/dexcount-gradle-plugin)

**Comment by avluis** [comment]
@amitav13 Thank you but I'm good -- I'm already aware of that but thanks anyways.

**Comment by carstenhag** [comment]
Just got the same error , about 2 years and a bit later :)

If a fix would be possible, that would be cool of course!

**Comment by cortinico** [comment]
@carstenhag Can you please provide version of AppIntro that you're using + an updated stacktrace?

**Comment by carstenhag** [comment]
@cortinico sure: v5.1.0

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference
       at com.github.paolorotolo.appintro.AppIntroBase.initController(AppIntroBase.java:328)
       at com.github.paolorotolo.appintro.AppIntroBase.onPostCreate(AppIntroBase.java:231)
       at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1385)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3088)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

```kotlin
class IntroActivity : AppIntro2() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_intro)

        showSkipButton(false)
        setFadeAnimation()

//...
```

**Comment by cortinico** [comment]
Hey @carstenhag 
Looks like your code is wrong. You shouldn't call `setContentView` in your `onCreate`.
Checkout the sample here https://github.com/AppIntro/AppIntro/blob/master/README.md

**Comment by carstenhag** [comment]
Yeah of course, I read that in this issue.

Read some earlier comments here, they talk about possibly adding a linter error.

**Comment by cortinico** [comment]
> Yeah of course, I read that in this issue.
> Read some earlier comments here, they talk about possibly adding a linter error.

Is your issue fixed?
I can think about writing a lint check about that, but is definitely a low priority task

**Comment by carstenhag** [comment]
Yep, issue is fixed.

Am Sa., 26. Jan. 2019, 15:46 hat Nicola Corti <notifications@github.com>
geschrieben:
