### ISSUE TITLE
Fabric + AppIntro

### ISSUE THREAD

**Issue by PaoloLoconsole** [paolorotolo/AppIntro#358]
Version of AppIntro you're running, for example: 4.1.0

**Stack trace / LogCat**:
Failed to execute task.
                                                                                java.util.concurrent.TimeoutException
                                                                                    at java.util.concurrent.FutureTask.get(FutureTask.java:176)
                                                                                    at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:44)
                                                                                    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:235)
                                                                                    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
11-18 12:08:28.119 5675-5675/it.aryonsolutions.printanywhere E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: it.aryonsolutions.printanywhere, PID: 5675
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{it....e.AndroidExplorer}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=630261345
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2316)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:147)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5253)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:949)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:744)
                                                                                Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=630261345
                                                                                   at android.support.v4.util.SimpleArrayMap.setValueAt(SimpleArrayMap.java:353)
                                                                                   at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:589)
                                                                                   at it....re.AndroidExplorer.onStart(AndroidExplorer.java:389)
                                                                                   at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
                                                                                   at android.app.Activity.performStart(Activity.java:5991)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5253) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:949) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:744) 
```ruby
paste stack trace and/or log here
```

**Comment by Andrew-Quebe** [comment]
You didn't provide any code...like...at all.

**Comment by PaoloLoconsole** [comment]
Initialing of Fabric
`try {
            Fabric.with(this, new Crashlytics());
            Crashlytics.log("AndroidExplorer.onCreate");
        } catch (Exception e) {
            Crashlytics.log("AndroidExplorer.onCreate --> error");
        }`


Code of ...AndroidExplorer.onStart(AndroidExplorer.java:389)

    @Override
    protected void onStart() {
        super.onStart();
    }

**Comment by avluis** [comment]
I can tell you from my experience with Crashlytics that this is not an AppIntro issue.
In fact, your AppIntro activity and the initialization of Crashlytics should not be anywhere in the same file.

Not sure where to point you afterwards, other than having you take a look at every single library that you are using (which shouldn't be giving issues) and checking stack.
