### ISSUE TITLE
NPE on missing back button

### ISSUE THREAD

**Issue by mtrakal** [paolorotolo/AppIntro#361]
**AppIntro Version**: 4.1.0

**Device/Android Version**: ANY

**Issue details / Repro steps / Use case background**: 
- create a custom view without back button `R.id.back`

**Your Code**: 
```java
public class OnboardingActivity extends AppIntro {
...
    @Override
    protected int getLayoutId() {
        return R.layout.activity_onboarding;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
...
}

```
View `activity_onboarding` does not contains R.id.back (with version `4.0.0` it works)

**Stack trace / LogCat**:
```ruby
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                                      at com.github.paolorotolo.appintro.AppIntroBase.onCreate(AppIntroBase.java:121)
                                                                                      at com.droid4you.application.wallet.component.onboarding.OnboardingActivity.onCreate(OnboardingActivity.java:46)
```

**Comment by Andrew-Quebe** [comment]
@mtrakal can you show me your full activity code? You shouldn't need to do anything with the back button.

**Comment by mtrakal** [comment]
It's not about activity. It's abous custom layout for AppIntor which we inject:

```
protected int getLayoutId() {
        return R.layout.activity_onboarding;
    }
```

`activity_onboarding.xml`  doesn't containts (because previous version does not required) 'R.id.back'.

**Comment by Andrew-Quebe** [comment]
@mtrakal so, what exactly needs to be done before 4.2.0 release?

**Comment by Andrew-Quebe** [comment]
Actually, it seems you made a PR...great! #362 needs to be updated however, because there are conflicts right now.

**Comment by Andrew-Quebe** [comment]
Closing until an update is provided by the creator.
