### ISSUE TITLE
transformDexArchiveWithExternalLibsDexMergerForDebug

### ISSUE THREAD

**Issue by upcwangying** [paolorotolo/AppIntro#593]
**AppIntro Version**: 5.0.1

**Device/Android Version**: 
virtual device : Pixel 2 7.1.1

**Issue details / Repro steps / Use case background**: 
I am running an empty activity Android app

**Your Code**: 
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.github.paolorotolo:appintro:v5.0.1'
}
```

**Stack trace / LogCat**:  Stack trace
```ruby
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myapplication:transformDexArchiveWithExternalLibsDexMergerForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\0.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\1.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\2.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\3.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\4.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\5.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\6.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\7.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\8.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\9.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\10.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\11.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\12.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\13.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\14.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\15.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\16.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\17.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\18.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\19.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\20.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\21.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\22.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\23.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\24.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\25.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\26.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\27.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\28.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\29.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\30.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\31.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\32.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\33.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\34.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\35.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\36.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\37.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\38.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\39.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\40.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\41.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\42.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\43.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\44.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\45.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\46.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\47.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\48.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\49.jar
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
	at sun.reflect.GeneratedMethodAccessor363.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 32 more
Caused by: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\0.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\1.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\2.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\3.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\4.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\5.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\6.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\7.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\8.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\9.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\10.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\11.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\12.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\13.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\14.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\15.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\16.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\17.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\18.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\19.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\20.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\21.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\22.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\23.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\24.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\25.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\26.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\27.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\28.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\29.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\30.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\31.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\32.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\33.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\34.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\35.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\36.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\37.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\38.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\39.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\40.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\41.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\42.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\43.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\44.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\45.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\46.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\47.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\48.jar, F:\work\AndroidStudioProjects\OrangeCat\myapplication\build\intermediates\transforms\dexBuilder\debug\49.jar
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:124)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:109)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:101)
	at com.android.build.gradle.internal.transforms.ExternalLibsMergerTransform.transform(ExternalLibsMergerTransform.kt:123)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	... 47 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:76)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
	at com.android.tools.r8.D8.run(D8.java:67)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:107)
	... 52 more
Caused by: com.android.tools.r8.utils.AbortException
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:77)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:58)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:67)
	... 55 more
```

**Comment by cortinico** [comment]
Hey @upcwangying 
Looks like you're using the non-AndroidX variants of the support library.

Can you please update your dependencies with the following?
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-beta02'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-beta02'
    implementation 'com.github.paolorotolo:appintro:v5.0.1'
}
```

AppIntro 5.x only compatible with AndroidX support libraries.
