### ISSUE TITLE
AppCompat does not support the current theme features

### ISSUE THREAD

**Issue by andreasjacobsen93** [PaoloRotolo/AppIntro#88]
Unable to start activity ComponentInfo{IntroActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features.

 UNHANDLED EXCEPTION:
 Java.Lang.IllegalArgumentException: Exception of type 'Java.Lang.IllegalArgumentException' was thrown.
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x00078>
 at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue*) 
 at Android.App.Activity.SetContentView (int) [0x00070] in Android.App.Activity.cs:5500
 at Model.Droid.AppIntro.OnCreate (Android.OS.Bundle) [0x00024] in AppIntro.cs:60
 at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (intptr,intptr,intptr) [0x00011] in Android.App.Activity.cs:2741
 at (wrapper dynamic-method) object.37f307ce-33a3-46e9-a351-053d3e1bd4c0 (intptr,intptr,intptr) <IL 0x00017, 0x00043>
 --- End of managed exception stack trace ---
 java.lang.IllegalArgumentException: AppCompat does not support the current theme features
 at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:363)
 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246)
 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
 at md545ee9dbd38e5e165dbd452039504aab4.AppIntro.n_onCreate(Native Method)
 at md545ee9dbd38e5e165dbd452039504aab4.AppIntro.onCreate(AppIntro.java:33)
 at android.app.Activity.performCreate(Activity.java:5231)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
 at android.app.ActivityThread.access$800(ActivityThread.java:135)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:136)
 at android.app.ActivityThread.main(ActivityThread.java:5001)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by Andrew-Quebe** [comment]
@andreasjacobsen93 can you provide your code that caused this issue? Please include your Intro activity code as well as where you start the activity (most likely in your MainActivity.java file).

**Comment by Andrew-Quebe** [comment]
Didn't mean to close the issue :P

**Comment by Andrew-Quebe** [comment]
@andreasjacobsen93 please reopen a new issue once that includes your code that caused this crash. Until then, I'm closing it. Thanks!
